### ISSUE TITLE
44916420012  MG

### ISSUE THREAD

**Issue by aercioneiva** [amdb-dev/valida-sintegra-php#1]
testei com a IE 44916420012 para MG e não funcionou
testei tbm com a IE 631041788 para RS e também não funcionou

**Comment by amdbstacks** [comment]
Olá, Aércio Ferreira Neiva, desculpe a demora em responder, o projeto ficou parado por um tempo. Analisei a questão acima, e na verdade o seu sistema está passando a IE sem os os zeros iniciais, uma das validações para esses estados, é o tamanho da inscrição, então o zero é considerado nesse caso.

0044916420012 - MG
0631041788 - RS

Com esses valores funcionará.
